version: "3.9"

services:
  web:
    container_name: web-server
    build:
      context: .
    environment:
      DB_URL: "sqlite:////app/data/rf_site.db"
      FASTAPI_NAME: "RF Analyzer"
    volumes:
      - db_data:/app/data/
    ports:
      - "80:8000"

volumes:
  db_data:
